// Centralized inline styles for DoCambridgeListeningTest
// Keeping this in a separate file reduces noise in the component file.

const createStyles = (isDarkMode = false) => {
  const colors = isDarkMode
    ? {
        pageBg: "#0f172a",
        surface: "#111827",
        surfaceAlt: "#16213e",
        text: "#e8e8e8",
        muted: "#b0b0b0",
        border: "#3d3d5c",
        primary: "#4a90d9",
        warning: "#f59e0b",
      }
    : {
        pageBg: "#f8fafc",
        surface: "#ffffff",
        surfaceAlt: "#f8fafc",
        text: "#0f172a",
        muted: "#475569",
        border: "#e5e7eb",
        primary: "#0e276f",
        warning: "#f59e0b",
      };

  return {
  container: {
    minHeight: '100vh',
    backgroundColor: colors.pageBg,
    color: colors.text,
    paddingBottom: '130px',
  },
  playGateOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(15, 23, 42, 0.6)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
    padding: '20px',
  },
  playGateCard: {
    width: '100%',
    maxWidth: '520px',
    background: colors.surface,
    borderRadius: '16px',
    padding: '22px 20px',
    textAlign: 'center',
    boxShadow: '0 20px 60px rgba(0,0,0,0.35)',
  },
  playGateButton: {
    background: colors.primary,
    color: '#fff',
    border: 'none',
    borderRadius: '999px',
    padding: '12px 18px',
    fontSize: '16px',
    fontWeight: 700,
    cursor: 'pointer',
    minWidth: '160px',
  },
  rubricBlock: {
    background: colors.surface,
    border: `1px solid ${colors.border}`,
    borderRadius: '12px',
    padding: '14px 16px',
    marginBottom: '14px',
  },
  rubricTitle: {
    margin: 0,
    fontSize: '16px',
    color: colors.text,
  },
  rubricText: {
    marginTop: '6px',
    fontSize: '14px',
    color: colors.muted,
  },
  pictureQuestionCard: {
    padding: '10px 0 18px',
    marginBottom: '18px',
    backgroundColor: 'transparent',
    borderBottom: `1px solid ${colors.border}`,
  },
  pictureQuestionHeader: {
    position: 'relative',
    marginBottom: '10px',
  },
  flagButton: {
    position: 'absolute',
    right: 0,
    top: 0,
    width: '34px',
    height: '34px',
    borderRadius: '10px',
    border: '1px solid transparent',
    background: 'transparent',
    cursor: 'pointer',
    fontSize: '16px',
    opacity: 0.85,
  },
  flagButtonActive: {
    opacity: 1,
  },
  pictureChoicesRow: {
    display: 'flex',
    gap: '34px',
    alignItems: 'flex-start',
    justifyContent: 'center',
    flexWrap: 'nowrap',
    padding: '12px 0 6px',
    overflowX: 'auto',
  },
  pictureChoiceItem: {
    width: '295px',
    flex: '0 0 295px',
  },
  pictureChoiceLabelWrap: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '10px',
    cursor: 'pointer',
    userSelect: 'none',
    borderRadius: '8px',
    padding: '6px',
  },
  pictureChoiceSelected: {
    outline: '2px solid rgba(14,39,111,0.22)',
    outlineOffset: '2px',
  },
  pictureChoiceCorrect: {
    outline: '2px solid rgba(34,197,94,0.35)',
    outlineOffset: '2px',
  },
  pictureChoiceWrong: {
    outline: '2px solid rgba(239,68,68,0.35)',
    outlineOffset: '2px',
  },
  pictureChoiceImage: {
    width: '295px',
    height: 'auto',
    display: 'block',
    borderRadius: '0px',
  },
  pictureChoiceImagePlaceholder: {
    width: '295px',
    height: '220px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: colors.muted,
    background: colors.surfaceAlt,
    borderRadius: '0px',
    fontSize: '12px',
  },
  pictureChoiceRadio: {
    marginTop: '6px',
  },
  audioTipWrap: {
    position: 'relative',
    marginLeft: '10px',
    flex: '0 0 auto',
  },
  audioTipButton: {
    width: '22px',
    height: '22px',
    borderRadius: '999px',
    border: `1px solid ${colors.border}`,
    background: colors.surface,
    color: colors.text,
    fontSize: '12px',
    fontWeight: 800,
    cursor: 'default',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    lineHeight: 1,
  },
  audioTipBubble: {
    position: 'absolute',
    right: 0,
    top: '28px',
    background: '#0f172a',
    color: '#ffffff',
    fontSize: '12px',
    padding: '8px 10px',
    borderRadius: '10px',
    whiteSpace: 'nowrap',
    boxShadow: '0 12px 30px rgba(0,0,0,0.22)',
    zIndex: 10,
  },
  footerBar: {
    position: 'fixed',
    left: 0,
    right: 0,
    bottom: 0,
    background: colors.surface,
    borderTop: `1px solid ${colors.border}`,
    zIndex: 1000,
    padding: '10px 12px',
  },
  footerNavButtons: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '8px',
  },
  footerArrowBtn: {
    width: '40px',
    height: '36px',
    borderRadius: '10px',
    border: `1px solid ${colors.border}`,
    background: colors.surfaceAlt,
    color: colors.text,
    cursor: 'pointer',
    fontSize: '18px',
    lineHeight: 1,
  },
  footerPartsRow: {
    display: 'flex',
    gap: '10px',
    alignItems: 'flex-start',
    overflowX: 'auto',
    paddingBottom: '4px',
  },
  footerPartWrapper: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    minWidth: '140px',
  },
  footerPartBtn: {
    border: '1px solid #e5e7eb',
    background: '#f8fafc',
    borderRadius: '12px',
    padding: '8px 10px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '8px',
    fontSize: '13px',
    color: '#0f172a',
  },
  footerPartBtnActive: {
    background: '#ffffff',
    borderColor: '#0e276f',
    boxShadow: '0 0 0 2px rgba(14,39,111,0.08)',
  },
  footerAttemptedCount: {
    fontSize: '12px',
    color: '#64748b',
    marginLeft: 'auto',
  },
  footerSubquestions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
  },
  footerSubquestionBtn: {
    width: '34px',
    height: '34px',
    borderRadius: '10px',
    border: '1px solid #e5e7eb',
    background: '#ffffff',
    cursor: 'pointer',
    fontSize: '12px',
    color: '#0f172a',
  },
  footerSubquestionAnswered: {
    background: '#ecfeff',
    borderColor: '#06b6d4',
  },
  footerSubquestionActive: {
    background: '#0e276f',
    borderColor: '#0e276f',
    color: '#ffffff',
  },
  footerDeliverBtn: {
    marginLeft: 'auto',
    width: '44px',
    height: '44px',
    borderRadius: '14px',
    border: '1px solid #e5e7eb',
    background: '#0e276f',
    color: '#ffffff',
    fontWeight: 900,
    cursor: 'pointer',
    flex: '0 0 auto',
  },
  loadingContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '100vh',
    backgroundColor: '#f8fafc',
  },
  errorContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '100vh',
    backgroundColor: '#f8fafc',
  },
  mainContent: {
    padding: '24px',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  questionArea: {
    backgroundColor: '#fff',
    borderRadius: '12px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
    padding: '24px',
  },
  partHeader: {
    marginBottom: '20px',
    paddingBottom: '16px',
    borderBottom: '2px solid #e5e7eb',
  },
  partInstruction: {
    margin: '12px 0 0',
    color: '#4b5563',
    fontSize: '15px',
    lineHeight: 1.6,
    backgroundColor: '#f0f9ff',
    padding: '12px 16px',
    borderRadius: '8px',
    borderLeft: '4px solid #3b82f6',
  },
  audioContainer: {
    display: 'flex',
    alignItems: 'center',
    padding: '16px',
    backgroundColor: '#f8fafc',
    borderRadius: '8px',
    marginBottom: '20px',
  },
  audioErrorBox: {
    marginTop: '-12px',
    marginBottom: '20px',
    padding: '12px 14px',
    backgroundColor: '#fff7ed',
    border: '1px solid #fed7aa',
    borderRadius: '10px',
    color: '#7c2d12',
    fontSize: '14px',
  },
  audioOpenLink: {
    display: 'inline-block',
    color: '#0e276f',
    fontWeight: 700,
    textDecoration: 'underline',
  },
  section: {
    marginBottom: '24px',
  },
  sectionTitle: {
    fontSize: '16px',
    fontWeight: 600,
    color: '#374151',
    margin: '0 0 16px',
    padding: '8px 12px',
    backgroundColor: '#f1f5f9',
    borderRadius: '6px',
  },
  questionCard: {
    padding: '16px',
    marginBottom: '16px',
    backgroundColor: '#fafafa',
    borderRadius: '8px',
    border: '1px solid #e5e7eb',
  },
  questionHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '12px',
    marginBottom: '12px',
  },
  questionNum: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '28px',
    height: '28px',
    backgroundColor: '#0e276f',
    color: '#fff',
    borderRadius: '50%',
    fontWeight: 600,
    fontSize: '13px',
    flexShrink: 0,
  },
  questionText: {
    flex: 1,
    fontSize: '15px',
    lineHeight: 1.5,
  },
  input: {
    width: '100%',
    padding: '10px 14px',
    border: '1px solid #d1d5db',
    borderRadius: '6px',
    fontSize: '15px',
    boxSizing: 'border-box',
    transition: 'border-color 0.2s',
  },
  correctAnswer: {
    marginTop: '8px',
    padding: '8px 12px',
    backgroundColor: '#dcfce7',
    color: '#166534',
    borderRadius: '6px',
    fontSize: '14px',
  },
  optionsContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  optionLabel: {
    display: 'flex',
    alignItems: 'center',
    padding: '12px',
    backgroundColor: '#fff',
    border: '1px solid #e5e7eb',
    borderRadius: '6px',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  optionSelected: {
    backgroundColor: '#dbeafe',
    borderColor: '#3b82f6',
  },
  optionCorrect: {
    backgroundColor: '#dcfce7',
    borderColor: '#22c55e',
  },
  optionWrong: {
    backgroundColor: '#fee2e2',
    borderColor: '#ef4444',
  },
  optionText: {
    flex: 1,
    fontSize: '14px',
  },
  matchingContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  matchingRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  matchingItem: {
    flex: 1,
    fontSize: '14px',
  },
  matchingSelect: {
    padding: '8px 12px',
    border: '1px solid #d1d5db',
    borderRadius: '6px',
    fontSize: '14px',
    minWidth: '200px',
  },
  rightItemsRef: {
    marginTop: '16px',
    padding: '12px',
    backgroundColor: '#f0f9ff',
    borderRadius: '8px',
  },
  rightItemBadge: {
    padding: '6px 12px',
    backgroundColor: '#fff',
    border: '1px solid #bae6fd',
    borderRadius: '6px',
    fontSize: '13px',
  },
  navButtons: {
    display: 'flex',
    justifyContent: 'space-between',
    marginTop: '24px',
    paddingTop: '20px',
    borderTop: '1px solid #e5e7eb',
  },
  navButton: {
    padding: '12px 24px',
    backgroundColor: '#0e276f',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: '14px',
    transition: 'all 0.2s',
  },
  navButtonDisabled: {
    backgroundColor: '#94a3b8',
    cursor: 'not-allowed',
  },
  resultsOverlay: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  resultsModal: {
    backgroundColor: 'white',
    padding: '32px',
    borderRadius: '16px',
    textAlign: 'center',
    maxWidth: '400px',
    width: '90%',
  },
  confirmModal: {
    backgroundColor: colors.surface,
    padding: '24px',
    borderRadius: '12px',
    textAlign: 'center',
    maxWidth: '360px',
    width: '90%',
  },
  scoreDisplay: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '24px',
    padding: '24px',
    backgroundColor: isDarkMode ? '#0f2a1a' : '#f0fdf4',
    borderRadius: '12px',
  },
  scoreNumber: {
    fontSize: '36px',
    fontWeight: 700,
    color: colors.primary,
  },
  scorePercent: {
    fontSize: '28px',
    fontWeight: 600,
    color: '#22c55e',
  },
  primaryButton: {
    padding: '12px 24px',
    backgroundColor: colors.primary,
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: '14px',
  },
  secondaryButton: {
    padding: '12px 24px',
    backgroundColor: colors.surfaceAlt,
    color: colors.text,
    border: `1px solid ${colors.border}`,
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: '14px',
  },
  backButton: {
    marginTop: '20px',
    padding: '12px 24px',
    backgroundColor: colors.primary,
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
  },
  };
};

export default createStyles;
