// Extracted from DoListeningTest.jsx to keep the page component lean.

const createStyles = (isDarkMode = false) => {
  const colors = isDarkMode
    ? {
        pageBg: "#0f172a",
        surface: "#111827",
        surfaceAlt: "#16213e",
        surfaceRaised: "#13203a",
        text: "#e8e8e8",
        muted: "#b0b0b0",
        border: "#3d3d5c",
        primary: "#4a90d9",
        primaryStrong: "#60a5fa",
        success: "#22c55e",
        warning: "#f59e0b",
        danger: "#dc2626",
        cardShadow: "0 24px 64px rgba(2, 6, 23, 0.45)",
        navBg: "rgba(15, 23, 42, 0.9)",
      }
    : {
        pageBg: "#eef4ff",
        surface: "#fff",
        surfaceAlt: "#f5f8ff",
        surfaceRaised: "#edf4ff",
        text: "#132238",
        muted: "#5d6b82",
        border: "#d6e0ef",
        primary: "#1d4ed8",
        primaryStrong: "#1e3a8a",
        success: "#15803d",
        warning: "#b45309",
        danger: "#b91c1c",
        cardShadow: "0 24px 70px rgba(30, 64, 175, 0.08)",
        navBg: "rgba(255, 255, 255, 0.92)",
      };

  return {
  surfaceColor: colors.surface,

  pageWrapper: {
    width: "100%",
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    fontFamily: "'Aptos', 'Segoe UI Variable Text', 'Trebuchet MS', sans-serif",
    fontWeight: 500,
    backgroundColor: colors.pageBg,
    background: isDarkMode
      ? "radial-gradient(circle at top, rgba(74,144,217,0.18), transparent 34%), linear-gradient(180deg, #0f172a 0%, #111827 100%)"
      : "radial-gradient(circle at top left, rgba(96,165,250,0.22), transparent 32%), radial-gradient(circle at top right, rgba(14,165,233,0.12), transparent 28%), linear-gradient(180deg, #f5f8ff 0%, #eef4ff 48%, #f8fbff 100%)",
    color: colors.text,
  },

  // Loading & Error
  loadingContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100vh",
    background: colors.pageBg,
  },
  spinner: {
    width: "48px",
    height: "48px",
    border: `4px solid ${colors.border}`,
    borderTopColor: colors.primary,
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
    marginBottom: "16px",
  },
  loadingText: { color: colors.muted, fontSize: "16px" },
  errorContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100vh",
    background: colors.pageBg,
  },
  errorTitle: { color: colors.danger, fontSize: "24px", marginBottom: "8px" },
  errorText: { color: colors.muted, marginBottom: "16px" },
  backButton: {
    padding: "12px 24px",
    background: `linear-gradient(135deg, ${colors.primary} 0%, ${colors.primaryStrong} 100%)`,
    color: "#fff",
    border: "none",
    borderRadius: "999px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: 700,
    boxShadow: colors.cardShadow,
  },

  // Header
  header: {
    borderBottom: `1px solid ${colors.border}`,
    backgroundColor: colors.surface,
  },
  headerContent: {
    display: "flex",
    alignItems: "center",
    padding: "0 16px",
    height: "56px",
  },
  logoWrapper: { padding: "8px 16px" },
  logoText: { fontSize: "20px", fontWeight: "bold", color: colors.primary },
  testInfo: { flex: 1, paddingLeft: "16px" },
  testTitle: { fontWeight: "bold", fontSize: "16px", color: colors.text },
  timeInfo: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "14px",
    color: colors.muted,
  },
  audioIcon: { fontSize: "16px" },
  submitButton: {
    padding: "8px 20px",
    backgroundColor: colors.success,
    color: "#fff",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: 600,
    fontSize: "14px",
  },

  // Part Info Box
  partInfoBox: {
    width: "min(1240px, calc(100% - 32px))",
    margin: "18px auto 0",
    padding: "24px 26px",
    background: isDarkMode
      ? `linear-gradient(135deg, ${colors.surfaceRaised} 0%, ${colors.surfaceAlt} 100%)`
      : "linear-gradient(135deg, rgba(255,255,255,0.98) 0%, rgba(239,246,255,0.96) 100%)",
    border: `1px solid ${colors.border}`,
    borderRadius: "24px",
    boxShadow: colors.cardShadow,
    backdropFilter: "blur(10px)",
  },
  partTitle: { fontWeight: 900, fontSize: "1.8rem", color: colors.primaryStrong, letterSpacing: "0.01em" },
  partDescription: { fontSize: "0.98rem", color: colors.muted, marginTop: "8px", lineHeight: 1.6 },

  // Main Content
  mainContent: {
    flex: 1,
    position: "relative",
    paddingBottom: "108px",
  },
  audioContainer: {
    width: "min(1240px, calc(100% - 48px))",
    margin: "0 auto 18px",
    padding: "16px 18px",
    borderRadius: "20px",
    border: `1px solid ${colors.border}`,
    background: isDarkMode
      ? `linear-gradient(135deg, ${colors.surfaceRaised} 0%, ${colors.surfaceAlt} 100%)`
      : "linear-gradient(135deg, rgba(255,255,255,0.98) 0%, rgba(248,250,252,0.96) 100%)",
    boxShadow: colors.cardShadow,
  },
  audioPlayer: { width: "100%", height: "40px" },
  playButtonSmall: { backgroundColor: colors.primary, color: "#fff", border: "none", borderRadius: "8px", padding: "10px 16px", cursor: "pointer", fontSize: "15px" },
  audioWarning: { color: colors.warning, fontSize: "13px", marginTop: "4px" },
  questionsList: {
    width: "min(1240px, calc(100% - 48px))",
    margin: "0 auto",
    padding: "4px 0 24px",
    overflowY: "auto",
    maxHeight: "calc(100vh - 280px)",
  },

  // Section
  sectionContainer: {
    marginBottom: "24px",
    padding: "22px",
    borderRadius: "28px",
    border: `1px solid ${colors.border}`,
    background: isDarkMode
      ? `linear-gradient(180deg, ${colors.surface} 0%, ${colors.surfaceAlt} 100%)`
      : "linear-gradient(180deg, rgba(255,255,255,0.98) 0%, rgba(247,250,255,0.96) 100%)",
    boxShadow: colors.cardShadow,
    backdropFilter: "blur(10px)",
  },
  sectionTitle: {
    fontWeight: 900,
    fontSize: "1.45rem",
    marginBottom: "10px",
    color: colors.primaryStrong,
    letterSpacing: "0.01em",
  },
  sectionInstruction: { marginBottom: "18px", color: colors.muted, lineHeight: 1.8, fontSize: "0.98rem" },
  questionsWrapper: { display: "flex", flexDirection: "column", gap: "14px" },

  // Multiple Choice
  questionItem: {
    marginBottom: "0",
    padding: "18px",
    borderRadius: "20px",
    background: colors.surface,
    border: `1px solid ${colors.border}`,
    boxShadow: "0 12px 28px rgba(15, 23, 42, 0.05)",
  },
  questionHeader: { display: "flex", gap: "14px", marginBottom: "12px", alignItems: "flex-start" },
  questionNumber: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "40px",
    height: "40px",
    background: `linear-gradient(135deg, ${colors.primary} 0%, ${colors.primaryStrong} 100%)`,
    color: "#fff",
    borderRadius: "14px",
    fontWeight: 800,
    fontSize: "15px",
    flexShrink: 0,
    boxShadow: "0 12px 24px rgba(37, 99, 235, 0.2)",
  },
  questionNumberWide: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "58px",
    height: "40px",
    background: `linear-gradient(135deg, ${colors.primary} 0%, ${colors.primaryStrong} 100%)`,
    color: "#fff",
    borderRadius: "14px",
    fontWeight: 800,
    fontSize: "14px",
    padding: "0 12px",
    flexShrink: 0,
    boxShadow: "0 12px 24px rgba(37, 99, 235, 0.18)",
  },
  questionText: { flex: 1, marginTop: "6px", lineHeight: 1.7, color: colors.text, fontSize: "1rem" },
  optionsList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  optionItem: { position: "relative" },
  optionLabel: {
    display: "flex",
    gap: "8px",
    padding: "12px 14px",
    borderRadius: "16px",
    backgroundColor: isDarkMode ? colors.surfaceAlt : colors.surfaceAlt,
    border: `1px solid ${colors.border}`,
    cursor: "pointer",
    transition: "background-color 0.2s, border-color 0.2s, transform 0.2s",
  },
  optionText: { marginLeft: "20px", color: colors.text, lineHeight: 1.55 },
  radioInput: {
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    left: "8px",
  },
  checkboxInput: {
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    left: "8px",
    backgroundColor: colors.surface,
  },

  // Fill Question
  fillQuestionItem: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    marginBottom: "0",
    padding: "16px 18px",
    borderRadius: "20px",
    background: colors.surface,
    border: `1px solid ${colors.border}`,
    boxShadow: "0 12px 28px rgba(15, 23, 42, 0.05)",
  },
  fillQuestionNumber: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "40px",
    height: "40px",
    background: `linear-gradient(135deg, ${colors.primary} 0%, ${colors.primaryStrong} 100%)`,
    color: "#fff",
    borderRadius: "14px",
    fontWeight: 800,
    fontSize: "15px",
    flexShrink: 0,
    boxShadow: "0 12px 24px rgba(37, 99, 235, 0.18)",
  },
  fillInput: {
    flex: 1,
    border: `1.5px solid ${colors.border}`,
    borderRadius: "14px",
    padding: "12px 14px",
    fontSize: "15px",
    outline: "none",
    backgroundColor: colors.surface,
    color: colors.text,
    boxShadow: "inset 0 1px 2px rgba(15, 23, 42, 0.04)",
  },
  fillQuestionsContainer: { display: "flex", flexDirection: "column" },

  // Multi-select (Choose TWO letters style)
  multiSelectContainer: {
    padding: "20px 22px",
    marginBottom: "0",
    borderRadius: "22px",
    border: `1px solid ${colors.border}`,
    background: isDarkMode
      ? `linear-gradient(180deg, ${colors.surface} 0%, ${colors.surfaceAlt} 100%)`
      : "linear-gradient(180deg, rgba(255,255,255,0.98) 0%, rgba(239,246,255,0.96) 100%)",
    boxShadow: "0 12px 28px rgba(15, 23, 42, 0.05)",
  },
  multiSelectHeader: {
    display: "flex",
    alignItems: "flex-start",
    gap: "12px",
    marginBottom: "12px",
  },
  multiSelectBadge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "7px 12px",
    background: `linear-gradient(135deg, ${colors.primary} 0%, ${colors.primaryStrong} 100%)`,
    color: "#fff",
    borderRadius: "12px",
    fontWeight: 800,
    fontSize: "14px",
    whiteSpace: "nowrap",
  },
  multiSelectQuestionText: {
    fontSize: "15px",
    color: colors.text,
    lineHeight: 1.5,
  },
  multiSelectOptions: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  multiSelectOption: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "12px 14px",
    border: `1px solid ${colors.border}`,
    borderRadius: "16px",
    backgroundColor: colors.surface,
    cursor: "pointer",
    transition: "all 0.2s",
  },
  multiSelectCheckbox: {
    width: "18px",
    height: "18px",
    cursor: "pointer",
  },
  multiSelectOptionText: {
    fontSize: "14px",
    color: colors.text,
  },

  // Matching
  matchingContainer: {
    display: "flex",
    flexDirection: "row",
    gap: "24px",
    flexWrap: "wrap",
  },
  matchingLeft: { flex: 1, minWidth: "280px" },
  matchingRight: { flex: 1, minWidth: "200px" },
  matchingItemsList: { display: "flex", flexDirection: "column", gap: "8px" },
  matchingRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "12px 14px",
    borderRadius: "16px",
    background: colors.surfaceAlt,
    border: `1px solid ${colors.border}`,
  },
  matchingQuestionNum: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "38px",
    height: "38px",
    background: `linear-gradient(135deg, ${colors.primary} 0%, ${colors.primaryStrong} 100%)`,
    color: "#fff",
    borderRadius: "12px",
    fontWeight: 800,
    fontSize: "14px",
    flexShrink: 0,
  },
  matchingItemText: { flex: 1 },
  matchingDropdownWrapper: { minWidth: "80px", position: "relative" },
  matchingSelect: {
    width: "100%",
    padding: "9px 12px",
    border: `1.5px solid ${colors.border}`,
    borderRadius: "12px",
    backgroundColor: colors.surface,
    color: colors.text,
    cursor: "pointer",
  },
  optionsTitle: { fontWeight: 600, marginBottom: "8px" },
  optionsContainer: { display: "flex", flexDirection: "column", gap: "4px" },
  optionCard: {
    padding: "12px 14px",
    border: `1px solid ${colors.border}`,
    borderRadius: "14px",
    backgroundColor: colors.surfaceAlt,
    color: colors.text,
    fontSize: "14px",
  },

  // Form/Table Completion - IELTS Style
  formContainer: {
    background: isDarkMode
      ? `linear-gradient(180deg, ${colors.surface} 0%, ${colors.surfaceAlt} 100%)`
      : "linear-gradient(180deg, rgba(255,255,255,0.98) 0%, rgba(239,246,255,0.96) 100%)",
    border: `1px solid ${colors.border}`,
    borderRadius: "24px",
    overflow: "hidden",
    boxShadow: "0 14px 32px rgba(15, 23, 42, 0.06)",
  },
  formContent: {
    padding: "20px 22px 22px",
    lineHeight: "2.55",
  },
  formRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "4px",
    flexWrap: "wrap",
  },
  formLabel: {
    fontWeight: "500",
    color: colors.text,
    minWidth: "fit-content",
  },
  formValue: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    flexWrap: "wrap",
  },
  formFixedValue: {
    color: colors.text,
    fontWeight: "500",
  },
  formGapWrapper: {
    display: "inline-flex",
    alignItems: "center",
  },
  formGapInput: {
    width: "168px",
    padding: "10px 12px",
    border: `1.5px solid ${colors.border}`,
    borderRadius: "14px",
    fontSize: "14px",
    outline: "none",
    backgroundColor: colors.surface,
    color: colors.text,
    transition: "border-color 0.2s, box-shadow 0.2s",
    fontWeight: 700,
  },

  // Legacy Form/Table styles (kept for compatibility)
  formTable: { overflowX: "auto" },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    border: `1px solid ${colors.border}`,
  },
  tableCell: {
    padding: "12px",
    border: `1px solid ${colors.border}`,
    verticalAlign: "middle",
    backgroundColor: colors.surface,
  },
  gapWrapper: { position: "relative", display: "inline-flex", marginLeft: "4px" },
  gapInput: {
    width: "120px",
    padding: "4px 8px",
    border: `1px solid ${colors.border}`,
    borderRadius: "4px",
    fontSize: "14px",
    outline: "none",
    backgroundColor: colors.surface,
    color: colors.text,
  },
  gapPlaceholder: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    color: colors.muted,
    pointerEvents: "none",
  },

  // Floating Navigation
  floatingNav: {
    position: "fixed",
    bottom: "96px",
    right: "24px",
    display: "flex",
    gap: "12px",
    zIndex: 80,
  },
  navArrowLeft: {
    width: "60px",
    height: "60px",
    background: isDarkMode ? "linear-gradient(135deg, #1f2b47 0%, #273754 100%)" : "linear-gradient(135deg, #64748b 0%, #334155 100%)",
    border: "none",
    borderRadius: "18px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 18px 30px rgba(15, 23, 42, 0.18)",
  },
  navArrowRight: {
    width: "60px",
    height: "60px",
    background: "linear-gradient(135deg, #111827 0%, #1e293b 100%)",
    border: "none",
    borderRadius: "18px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 18px 30px rgba(15, 23, 42, 0.22)",
  },

  // Bottom Navigation
  bottomNav: {
    position: "fixed",
    bottom: 0,
    left: 0,
    right: 0,
    background: colors.navBg,
    borderTop: `1px solid ${colors.border}`,
    zIndex: 30,
    boxShadow: "0 -16px 34px rgba(15, 23, 42, 0.12)",
    backdropFilter: "blur(18px)",
  },
  partsContainer: {
    display: "flex",
    alignItems: "stretch",
    overflowX: "auto",
    overflowY: "hidden",
    gap: "12px",
    padding: "12px 16px 14px",
    scrollbarWidth: "thin",
    WebkitOverflowScrolling: "touch",
  },
  partTab: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    flex: "0 0 172px",
    minWidth: "172px",
    maxWidth: "172px",
    padding: "14px 16px",
    cursor: "pointer",
    border: `1px solid ${colors.border}`,
    borderRadius: "20px",
    transition: "background-color 0.2s",
    boxShadow: isDarkMode ? "none" : "0 8px 18px rgba(15, 23, 42, 0.04)",
    overflow: "hidden",
  },
  partLabel: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    whiteSpace: "nowrap",
  },
  partLabelText: { fontWeight: "800", fontSize: "16px", color: colors.primaryStrong },
  partProgress: { fontSize: "14px", color: colors.muted },
  questionNumbers: {
    display: "flex",
    flexWrap: "nowrap",
    gap: "10px",
    marginTop: "12px",
    justifyContent: "flex-start",
    width: "100%",
    overflow: "hidden",
  },
  questionNumBox: {
    minWidth: "34px",
    height: "34px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: isDarkMode ? `1px solid ${colors.border}` : "1px solid transparent",
    borderRadius: "12px",
    fontSize: "14px",
    cursor: "pointer",
    backgroundColor: colors.surface,
    color: colors.text,
    padding: "0 6px",
    fontWeight: 700,
    flex: "0 0 auto",
  },
  questionNumBoxWide: {
    minWidth: "48px",
    padding: "0 10px",
    fontSize: "14px",
  },
  submitIcon: {
    flex: "0 0 72px",
    minWidth: "72px",
    padding: "16px 18px",
    background: `linear-gradient(135deg, ${colors.primaryStrong} 0%, ${colors.primary} 100%)`,
    color: "#fff",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "20px",
    boxShadow: "0 12px 30px rgba(29, 78, 216, 0.22)",
  },

  // Modals
  modalOverlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(0,0,0,0.6)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 50,
  },
  modalContent: {
    backgroundColor: colors.surface,
    padding: "28px",
    borderRadius: "16px",
    maxWidth: "480px",
    width: "90%",
    boxShadow: "0 8px 32px rgba(0,0,0,0.25)",
  },
  modalTitle: {
    fontSize: "20px",
    fontWeight: "bold",
    color: colors.primary,
    marginBottom: "16px",
  },
  modalText: { marginBottom: "16px", color: colors.muted },
  summaryBox: {
    padding: "12px",
    backgroundColor: colors.surfaceAlt,
    borderRadius: "8px",
    marginBottom: "16px",
  },
  summaryLabel: { fontSize: "13px", color: colors.muted, marginBottom: "8px" },
  summaryRow: {
    display: "flex",
    justifyContent: "space-between",
    padding: "4px 0",
    fontSize: "14px",
  },
  warningText: { color: colors.danger, fontSize: "13px", marginBottom: "16px" },
  modalButtons: { display: "flex", gap: "12px", justifyContent: "flex-end" },
  cancelButton: {
    padding: "10px 20px",
    backgroundColor: colors.surfaceAlt,
    color: colors.text,
    border: `1px solid ${colors.border}`,
    borderRadius: "8px",
    cursor: "pointer",
    fontWeight: 500,
    fontSize: "14px",
  },
  confirmButton: {
    padding: "10px 24px",
    backgroundColor: colors.success,
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    fontWeight: 600,
    fontSize: "14px",
  },

  // Play gate (Cambridge-style start modal)
  playGateOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(15, 23, 42, 0.6)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
    padding: '20px',
  },
  playGateCard: {
    width: '100%',
    maxWidth: '520px',
    background: colors.surface,
    borderRadius: '16px',
    padding: '22px 20px',
    textAlign: 'center',
    boxShadow: '0 20px 60px rgba(0,0,0,0.35)',
  },
  playGateButton: {
    background: colors.primary,
    color: '#fff',
    border: 'none',
    borderRadius: '999px',
    padding: '12px 18px',
    fontSize: '16px',
    fontWeight: 700,
    cursor: 'pointer',
    minWidth: '160px',
  },
  audioErrorBox: {
    marginTop: '-12px',
    marginBottom: '20px',
    padding: '12px 14px',
    backgroundColor: isDarkMode ? '#3a1f0f' : '#fff7ed',
    border: isDarkMode ? '1px solid #7c2d12' : '1px solid #fed7aa',
    borderRadius: '10px',
    color: isDarkMode ? '#fbd38d' : '#7c2d12',
    fontSize: '14px',
  },
  audioOpenLink: {
    display: 'inline-block',
    color: colors.primary,
    fontWeight: 700,
    textDecoration: 'underline',
  },

  // Play button style (KET modal)
  playButton: {
    padding: "12px 28px",
    backgroundColor: colors.primary,
    color: "#fff",
    borderRadius: "999px",
    border: "none",
    cursor: "pointer",
    fontSize: "16px",
    display: "inline-flex",
    alignItems: "center",
    gap: "12px",
    boxShadow: "0 6px 18px rgba(14,39,111,0.15)",
  },

  // Results (legacy keys; kept because some JSX still references them)
  resultsTitle: {
    fontSize: "20px",
    fontWeight: "bold",
    color: "#15803d",
    textAlign: "center",
    marginBottom: "16px",
  },
  scoreBox: {
    textAlign: "center",
    padding: "24px",
    backgroundColor: isDarkMode ? "#0f2a1a" : "#f0fdf4",
    borderRadius: "12px",
    marginBottom: "20px",
  },
  scoreNumber: { fontSize: "48px", fontWeight: "bold", color: "#16a34a" },
  scoreLabel: { color: colors.muted, marginTop: "8px" },
  bandScore: {
    display: "inline-block",
    marginTop: "16px",
    padding: "8px 16px",
    backgroundColor: colors.surface,
    borderRadius: "8px",
  },
  bandLabel: { fontSize: "13px", color: colors.muted },
  bandValue: { fontSize: "20px", fontWeight: "bold", color: colors.primary },
  resultsButtons: { display: "flex", gap: "12px", justifyContent: "center" },

  // Notes Completion
  notesContainer: {
    background: isDarkMode
      ? `linear-gradient(180deg, ${colors.surface} 0%, ${colors.surfaceAlt} 100%)`
      : "linear-gradient(180deg, rgba(255,255,255,0.98) 0%, rgba(239,246,255,0.96) 100%)",
    border: `1px solid ${colors.border}`,
    borderRadius: "24px",
    padding: "20px 22px",
    boxShadow: "0 14px 32px rgba(15, 23, 42, 0.06)",
  },
  notesTitle: {
    fontWeight: 800,
    fontSize: "16px",
    marginBottom: "14px",
    color: colors.primaryStrong,
  },
  notesContent: {
    lineHeight: 1.95,
    fontSize: "14px",
  },
  notesLine: {
    marginBottom: "8px",
    display: "block",
  },
  notesBlank: {
    display: "inline-block",
    borderBottom: "1px solid #999",
    minWidth: "60px",
  },

  // Form Title
  formTitle: {
    fontWeight: 800,
    fontSize: "15px",
    marginBottom: "12px",
    padding: "12px 16px",
    background: isDarkMode
      ? `linear-gradient(135deg, ${colors.surfaceRaised} 0%, ${colors.surfaceAlt} 100%)`
      : "linear-gradient(135deg, rgba(219,234,254,0.95) 0%, rgba(239,246,255,0.95) 100%)",
    color: colors.primaryStrong,
    borderRadius: "18px 18px 12px 12px",
  },
  };
};

export default createStyles;
