name: Update DB Config
on:
  workflow_dispatch:  # Cho phép chạy thủ công từ GitHub
  push:
    paths:
      - 'backend/db.js'
      - 'backend/.env*'

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Update DB Configuration
      run: |
        echo "<?php
        // Tạo file .env mới
        \$env_content = '
        NODE_ENV=production
        PORT=3000
        PROD_DB_HOST=localhost
        PROD_DB_NAME=wsxcblqh_ix
        PROD_DB_USER=wsxcblqh_thanh
        PROD_DB_PASS=@Thanh562184
        ';
        
        file_put_contents('/home/wsxcblqh/ix.star-siec.edu.vn/backend/.env', \$env_content);
        
        // Restart server để áp dụng cấu hình mới
        shell_exec('/usr/local/bin/pm2 restart server');
        
        echo 'Database configuration updated and server restarted';
        ?>" > update-db.php
        
        # Upload và thực thi script
        curl -T update-db.php "ftp://${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}@star-siec.edu.vn/ix.star-siec.edu.vn/"
        curl "https://ix.star-siec.edu.vn/update-db.php"
        rm update-db.php